from .clear import clear
from .help import help
from .prompt import prompt
from .ratings import ratings
from .my_rating import my_rating
from .top_na import top_na
from .view_rating import view_rating
from .get_id import get_id
from .t8ball import the8ball
from .motm import motm
from .joke import joke
from .view_league_table import league_table
from .view_top_scorers import top_scorers
from .view_tournament import tournament
from .translate_english import translate_english
from .translate_spanish import translate_spanish